name: "\U0001F680 New feature proposal"
description: Propose a new feature to be added to one if not all our services
title: "[Feature]: "
labels: ["c: new feature"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to complete this form!
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/jessesquires/.github/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly and concisely describe what you would like to change, add, or implement.
      placeholder: Tell us your idea.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
      placeholder: What problem will this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this be solved?
      placeholder: How do you think this should be implemented?
    validations:
      required: true
  - type: dropdown
    id: target
    attributes:
      label: Target HSS Software
      description: Which software within HSS should utilize this feature?
      multiple: true
      options: 
        - HilDesktop
        - HilMobile
        - HSS-Web
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other possible approaches?
      placeholder: Can you think of any other options?
    validations:
      required: true
